### ISSUE TITLE
DRM protected stream not supported

### ISSUE THREAD

**Issue by nodomain** [bromix/plugin.video.vox-now.de#3]
Hi,
I can't use the plugin in the newest version from your repository with all RTL sites.

Please try to fix it :-)

**Comment by bromix** [comment]
Not possible...that's why you see the notification ;)

**Comment by bromix** [comment]
I try something tomorrow (if I find some time)...but this looks bad.

**Comment by nodomain** [comment]
This would be awesome! Perhaps this helps somehow: http://rtl-now.rtl.de/hilfe_Linux_Ubuntu.php

**Comment by bromix** [comment]
Thanks for the info...I look into it....for now I could fix RTL, RTL II and VOX..N-TV is completely DRM protected.
